env: "local" #определяем окружение в котором планируем запускать приложение (local, dev, prod etc.)
storage_path: "/storage/storage.db"     #задаем путь хранения базы данных
http_server:                            #задаем http сервер со вложенными полями
   adress: "localhost:8085"             #задаем адрес-порт. 8085 вместо 8080 для подстраховки, если что-то уже будет по дефолту на 8080
   timeout: 4s                          #задаем время на обработку запроса
   iddle_timeout: 60s                   #задаем время жизни соединения с клиентом